name: github workflow 
on:
  push: 
    branches:[main]
  workflow_dispatch:
jobs:
  hello-jobs:
    name:hwllo-world
    runs-on: ubuntu-latest 

    steps:
      -name: checkout code
       uses:actions/checkout
      # Step 2: Print a simple message
      
      